update kohana aliases
codex-team/kohana-aliases pull request #5
Opened 2018-04-04 13:15 UTC by talyguryn

2018-04-04 13:24 UTC, gohabereg requested changes

2018-04-04 13:24 UTC, gohabereg commented on README.md
> +This module allows you to make usefull and beautifull URLs for your service.
Не позорься

2018-04-04 13:24 UTC, gohabereg commented on README.md
> +You don't need more `/user/<id>` or `/article/<id>` cursors in routes. Now you can use simply `/donald` and `/victory` or `/pokemon-go` like addresses for different resources.
`simply /donald` звучит не очень

2018-04-04 13:24 UTC, gohabereg commented on README.md
> +All you need after is to incule alias creation and updating at your logic:
`include aliases creation and update methods into your logic`

2018-04-04 13:24 UTC, gohabereg commented on README.md
> +### Creating
Было лучше

2018-04-04 13:24 UTC, gohabereg commented on README.md
> +Note that module's version does not includes a cache scheme. You may need `memcache` or another driver to add this feature.
У тебя уже есть does, не нужно s

2018-04-04 13:24 UTC, gohabereg commented on classes/Dao/Alias.php
> +class Dao_Alias extends Dao_MySQL_Base
`Dao_MySQL_Base` это кохановский класс?

2018-04-04 13:25 UTC, gohabereg requested changes

2018-04-04 13:25 UTC, gohabereg commented on README.md
> +### Creating
Оставь как было

2018-04-04 13:30 UTC, neSpecc requested changes

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +You don't need more `/user/<id>` or `/article/<id>` cursors in routes. Now you can use simply `/donald` and `/victory` or `/pokemon-go` like addresses for different resources.
`simply` лучше перед use

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +This module allows you to make usefull and beautifull URLs for your service.
wrong

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +All you need after is to incule alias creation and updating at your logic:
include

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +### Creating
Resource creation

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +### Updating
Resource updating

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +### Creating
Resource creation

2018-04-04 13:30 UTC, neSpecc commented on README.md
> +You need no more `/user/<id>` or `/article/<id>` cursors in routes. Now you can use simply `/donald` and `/victory` or `/pokemon-go` like addresses for different resources.
You don't need more

2018-04-04 13:30 UTC, neSpecc commented on classes/Dao/Alias.php
> +<?php defined('SYSPATH') or die('No direct script access.');
remove Dao

2018-04-04 13:30 UTC, neSpecc commented on classes/Model/Alias.php
> +    public $target_type;
resource_type, resource_id,

2018-04-04 13:30 UTC, neSpecc commented on classes/Model/Alias.php
> +        return Dao_Alias::insert()
remove dao

2018-04-04 13:30 UTC, neSpecc commented on classes/Model/Alias.php
> +            {
???

2018-04-04 13:30 UTC, neSpecc commented on classes/Model/Alias.php
>       * @throws HTTP_Exception_404
не все  Exception указаны

2018-04-04 13:30 UTC, neSpecc commented on classes/Model/Alias.php
> +    public static function getAlias($route = null)
документация

2018-04-04 13:30 UTC, neSpecc commented on classes/Model/Kohana/Uri.php
> +    /**
where is types?

2018-04-14 18:25 UTC, khaydarov requested changes

2018-04-14 18:25 UTC, khaydarov commented on README.md
> +Fell free to give us a feedback on <a href="mailto::team@ifmo.su">team@ifmo.su</a>
Feel

2018-04-14 18:34 UTC, khaydarov approved these changes

2018-04-17 12:50 UTC, neSpecc requested changes

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +It means than entity `ARTICLE` requires controller with name `Articles`.
than -> that
requires -> will be handled by

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +`Controller/Users/Modify.php` with all other actions e.g. `action_add`, `action_edit`, `action_delete`.
_edit -> _ban

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +All you need after is to include aliases creation and update methods into your logic.
updating

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +### Set system routes
the

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +### Set system routes
+ describe what system aliases is.

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +Lock any count of system uries by adding them to array.
URIs
to the array

2018-04-17 12:50 UTC, neSpecc commented on README.md
> +Migrations for Aliases table in MySQL database migrations are in the [migrations/Aliases.sql](migrations/Aliases.sql) file.
for the
remove second migrations

2018-04-17 12:50 UTC, neSpecc commented on classes/Kohana/Model/Aliases.php
> +    public function __construct($uri = null, $type = null, $id = null, $dt_create = null, $deprecated = 0)
describe paramètres

2018-04-17 12:50 UTC, neSpecc commented on classes/Kohana/Model/Aliases.php
> +    public $uri;
describe properties

2018-04-17 12:50 UTC, neSpecc commented on classes/Kohana/Model/DB/Aliases.php
> +                    ->values(array(
fix code style

2018-04-17 12:50 UTC, neSpecc commented on classes/Kohana/Model/DB/Aliases.php
> +                    ->where('hash', '=', $hash)
code style

2018-04-17 12:50 UTC, neSpecc commented on init.php
> +        function (Route $route, $params, Request $request) {
fix code style

2018-04-17 14:46 UTC, neSpecc approved these changes

2018-04-17 14:46 UTC, merged